"""create enigma table

Revision ID: 2c161e9849e0
Revises: 
Create Date: 2019-04-09 23:44:13.313516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c161e9849e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enigma',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('secret', sa.String(length=40), nullable=False),
        sa.Column('target_url', sa.String(length=120), nullable=False),
        sa.Column('webhook_url', sa.String(length=120), nullable=True),
        sa.Column('discovery_count', sa.Integer(), nullable=False, server_default='0'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('secret')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enigma')
    # ### end Alembic commands ###
